import { Student, SubjectPerformance, GradeData } from '.';

// Complete student data from CSV (first 10 students as example)
export const studentsData: Student[] = [
  {
    Name: "Aarav Kumar",
    RollNo: "CSE1001",
    Sex: "Female",
    Age: 22,
    Address: "Rural",
    PhoneNumber: "9350251922",
    FamilySize: "Small",
    ParentsOccupation: "Private Job",
    TravelTime: "<15 min",
    ScholarType: "Day Scholar",
    StudyTime: "Low",
    Attendance: 68,
    AssignmentSubmission: "Missing",
    MarksAverage: 52,
    Scholarship: "No",
    HealthIssues: "Diabetes",
    ExtraCurricularActivities: "Sports"
  },
  {
    Name: "Diya Sharma",
    RollNo: "CSE1002",
    Sex: "Female",
    Age: 18,
    Address: "Urban",
    PhoneNumber: "9965943335",
    FamilySize: "Large",
    ParentsOccupation: "Farmer",
    TravelTime: "15-30 min",
    ScholarType: "Hosteller",
    StudyTime: "Medium",
    Attendance: 94,
    AssignmentSubmission: "On Time",
    MarksAverage: 87,
    Scholarship: "Yes",
    HealthIssues: "Asthma",
    ExtraCurricularActivities: "None"
  },
  {
    Name: "Vikram Patel",
    RollNo: "CSE1003",
    Sex: "Male",
    Age: 21,
    Address: "Urban",
    PhoneNumber: "9518643366",
    FamilySize: "Medium",
    ParentsOccupation: "Private Job",
    TravelTime: "<15 min",
    ScholarType: "Hosteller",
    StudyTime: "Low",
    Attendance: 68,
    AssignmentSubmission: "Late",
    MarksAverage: 51,
    Scholarship: "Yes",
    HealthIssues: "Migraine",
    ExtraCurricularActivities: "None"
  },
  {
    Name: "Sneha Reddy",
    RollNo: "CSE1004",
    Sex: "Female",
    Age: 23,
    Address: "Rural",
    PhoneNumber: "9798317959",
    FamilySize: "Small",
    ParentsOccupation: "Government Job",
    TravelTime: "<15 min",
    ScholarType: "Hosteller",
    StudyTime: "High",
    Attendance: 92,
    AssignmentSubmission: "Late",
    MarksAverage: 77,
    Scholarship: "No",
    HealthIssues: "Diabetes",
    ExtraCurricularActivities: "NSS"
  },
  {
    Name: "Arjun Nair",
    RollNo: "CSE1005",
    Sex: "Female",
    Age: 21,
    Address: "Rural",
    PhoneNumber: "9978346382",
    FamilySize: "Large",
    ParentsOccupation: "Business",
    TravelTime: "15-30 min",
    ScholarType: "Hosteller",
    StudyTime: "High",
    Attendance: 75,
    AssignmentSubmission: "Late",
    MarksAverage: 69,
    Scholarship: "Yes",
    HealthIssues: "None",
    ExtraCurricularActivities: "None"
  },
  {
    Name: "Kavya Iyer",
    RollNo: "CSE1006",
    Sex: "Female",
    Age: 21,
    Address: "Rural",
    PhoneNumber: "9159087995",
    FamilySize: "Large",
    ParentsOccupation: "Farmer",
    TravelTime: "15-30 min",
    ScholarType: "Day Scholar",
    StudyTime: "High",
    Attendance: 89,
    AssignmentSubmission: "Missing",
    MarksAverage: 57,
    Scholarship: "Yes",
    HealthIssues: "Diabetes",
    ExtraCurricularActivities: "NCC"
  },
  {
    Name: "Rahul Verma",
    RollNo: "CSE1007",
    Sex: "Male",
    Age: 20,
    Address: "Urban",
    PhoneNumber: "9401902852",
    FamilySize: "Small",
    ParentsOccupation: "Business",
    TravelTime: ">1 hr",
    ScholarType: "Day Scholar",
    StudyTime: "Low",
    Attendance: 83,
    AssignmentSubmission: "Late",
    MarksAverage: 94,
    Scholarship: "Yes",
    HealthIssues: "Diabetes",
    ExtraCurricularActivities: "Music"
  },
  {
    Name: "Meera Joshi",
    RollNo: "CSE1008",
    Sex: "Male",
    Age: 18,
    Address: "Urban",
    PhoneNumber: "9165057289",
    FamilySize: "Medium",
    ParentsOccupation: "Government Job",
    TravelTime: "<15 min",
    ScholarType: "Day Scholar",
    StudyTime: "Low",
    Attendance: 96,
    AssignmentSubmission: "On Time",
    MarksAverage: 83,
    Scholarship: "No",
    HealthIssues: "Asthma",
    ExtraCurricularActivities: "Dance"
  },
  {
    Name: "Karthik Raj",
    RollNo: "CSE1009",
    Sex: "Female",
    Age: 23,
    Address: "Urban",
    PhoneNumber: "9183012927",
    FamilySize: "Small",
    ParentsOccupation: "Government Job",
    TravelTime: "15-30 min",
    ScholarType: "Hosteller",
    StudyTime: "High",
    Attendance: 98,
    AssignmentSubmission: "Late",
    MarksAverage: 72,
    Scholarship: "Yes",
    HealthIssues: "Diabetes",
    ExtraCurricularActivities: "NSS"
  },
  {
    Name: "Ananya Singh",
    RollNo: "CSE1010",
    Sex: "Male",
    Age: 20,
    Address: "Urban",
    PhoneNumber: "9029092654",
    FamilySize: "Large",
    ParentsOccupation: "Private Job",
    TravelTime: ">1 hr",
    ScholarType: "Hosteller",
    StudyTime: "High",
    Attendance: 86,
    AssignmentSubmission: "On Time",
    MarksAverage: 73,
    Scholarship: "No",
    HealthIssues: "None",
    ExtraCurricularActivities: "NSS"
  }
  // Add remaining 40 students here...
];

export const subjects: SubjectPerformance[] = [
  { name: 'Maths', average: 75.2 },
  { name: 'English', average: 78.5 },
  { name: 'Science', average: 72.3 },
  { name: 'Arts', average: 81.1 },
  { name: 'Exercise', average: 85.6 },
  { name: 'Mandarin', average: 70.4 },
];

export const gradeData: GradeData[] = [
  { grade: 'Grade 1', count: 289, percentage: 28.9 },
  { grade: 'Grade 2', count: 222, percentage: 22.2 },
  { grade: 'Grade 3', count: 289, percentage: 28.9 },
  { grade: 'Grade 4', count: 153, percentage: 15.3 },
  { grade: 'Grade 5', count: 198, percentage: 19.8 },
];

export const topStudents = [
  { name: "Corny Niang", grade: "Grade 3", marks: 79.3 },
  { name: "Luka Magic", grade: "Grade 4", marks: 73.7 },
  { name: "Bianca Shangwe", grade: "Grade 2", marks: 63.7 },
  { name: "Alpha Kenya", grade: "Grade 5", marks: 83.1 },
];